
// Generated by Cadence Encounter(R) RTL Compiler v12.10-s012_1

// Verification Directory fv/c17 

module c17(N1, N2, N3, N6, N7, N22, N23);
  input N1, N2, N3, N6, N7;
  output N22, N23;
  wire N1, N2, N3, N6, N7;
  wire N22, N23;
  wire n_0, n_1, n_2, n_3, n_4;
  NAND2X1 g50(.A (n_4), .B (n_1), .Y (N22));
  OAI21X1 g51(.A (n_0), .B (n_3), .C (n_4), .Y (N23));
  NAND2X1 g52(.A (n_2), .B (N2), .Y (n_4));
  INVX1 g54(.A (n_2), .Y (n_3));
  NAND2X1 g53(.A (N1), .B (N3), .Y (n_1));
  NAND2X1 g55(.A (N6), .B (N3), .Y (n_2));
  INVX1 g56(.A (N7), .Y (n_0));
endmodule

